/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.woniu.sncp.cbss.api.core.thrift;


@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class ApiConstants {

  public static final String VERSION = "0.0.1";

  public static final int PARAM_RESOLVE_TYPE_DEFAULT = 1;

  public static final String ECHO_DATA_RESOLVE_TYPE_DEFAULT = "1";

  public static final int SIGNATURE_TYPE_DEFAULT = 1;

  public static final String TRACE_OPEN_CLIENT_STATE = "1";

}
