/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.woniu.sncp.cbss.api.core.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Status implements org.apache.thrift.TEnum {
  DEAD(0),
  STARTING(1),
  ALIVE(2),
  STOPPING(3),
  STOPPED(4),
  WARNING(5),
  FUTURE_STOPED(6),
  FUTURE_MAINTAIN(7);

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Status findByValue(int value) { 
    switch (value) {
      case 0:
        return DEAD;
      case 1:
        return STARTING;
      case 2:
        return ALIVE;
      case 3:
        return STOPPING;
      case 4:
        return STOPPED;
      case 5:
        return WARNING;
      case 6:
        return FUTURE_STOPED;
      case 7:
        return FUTURE_MAINTAIN;
      default:
        return null;
    }
  }
}
