spring:
  datasource: 
     url: jdbc:mysql://10.200.0.161:3306/SN_PAY?characterEncoding=UTF-8&useSSL=false
     username: SN_PAY
     password: snailgame
     driverClassName: com.mysql.jdbc.Driver
     test-on-borrow: true
     test-while-idle: true
     validation-query: select CURRENT_DATE;
     maxActive: 10
     maxIdle: 5
  queue-datasource: 
     url: jdbc:mysql://10.200.0.161:3306/SN_QUEUE?characterEncoding=UTF-8&useSSL=false
     username: SN_QUEUE
     password: snailgame
     driverClassName: com.mysql.jdbc.Driver
     test-on-borrow: true
     test-while-idle: true
     validation-query: select CURRENT_DATE;
     maxActive: 10
     maxIdle: 5
  jpa:
    show-sql: true
    hibernate: 
     naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  mvc:
   view:
    prefix: /WEB-INF/view
    suffix: .jsp
#cas client config
  cas: 
    sign-out-filters: /logout
    auth-filters: /sso/**,/m/sso/**,/security/*,/security/ttb/pay
    validate-filters: /*
    request-wrapper-filters: /*
    assertion-filters: /*
    cas-server-login-url: /login
    cas-server-m-login-url: /m/login
    cas-server-url-prefix: https://sso.woniu.com
    redirect-after-validation: true
    use-session: true
    server-name: http://cashier.woniu.com
    
#redis cluster
  redis: 
    cluster: 
      nodes: 
        - 10.106.0.199:7000
        - 10.106.0.199:7001
        - 10.106.0.199:7002
      timeout: 3000
  
  
