/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.woniu.sncp.cbss.api.core.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Status implements org.apache.thrift.TEnum {
  SERVER_DEAD(0),
  SERVER_ALIVE(1),
  SERVER_STARTING(2),
  SERVER_STOPPING(3),
  SERVER_STOPPED(4),
  SERVER_WARNING(5),
  SERVER_FUTURE_STOPED(6),
  SERVER_FUTURE_MAINTAIN(7),
  DOMAINNAME_CHANGE(8);

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Status findByValue(int value) { 
    switch (value) {
      case 0:
        return SERVER_DEAD;
      case 1:
        return SERVER_ALIVE;
      case 2:
        return SERVER_STARTING;
      case 3:
        return SERVER_STOPPING;
      case 4:
        return SERVER_STOPPED;
      case 5:
        return SERVER_WARNING;
      case 6:
        return SERVER_FUTURE_STOPED;
      case 7:
        return SERVER_FUTURE_MAINTAIN;
      case 8:
        return DOMAINNAME_CHANGE;
      default:
        return null;
    }
  }
}
