spring:
  datasource:
    url: jdbc:oracle:thin:@10.17.0.200:1521:center
    username: sn_account
    password: o_account_xn
    driverClassName: oracle.jdbc.driver.OracleDriver
    test-on-borrow: true
    test-while-idle: true
    validation-query: select 1 from dual;
    maxActive: 10
    maxIdle: 5
  jpa:
    show-sql: true
    
dubbo:
  zookeeper: zookeeper://192.168.1.128:2181
  port: 20051