
ALTER TABLE `SN_PAY`.`PAY_ORDER`
ADD COLUMN `N_MONEY_DISCOUNT_BEFORE`  decimal(10,2) NULL   ,
ADD COLUMN `N_MONEY_DISCOUNT_AFTER`  decimal(10,2) NULL    ,
ADD COLUMN `N_MONEY_DISCOUNT_CHANGE`  decimal(10,2) NULL     ;

CREATE TABLE `SN_PAY`.`PAY_ORDER_DISCOUNT` (
`N_ID`  integer NOT NULL AUTO_INCREMENT ,
`N_MERCHANT_ID`  integer UNSIGNED  NOT NULL   ,
`N_PAYMENT_ID`   integer UNSIGNED   NOT NULL  ,
`N_VALUE`  decimal(10,2)    NOT NULL  ,
`S_CALC_STANDARD`  VARCHAR (6) NOT NULL ,
`S_DISCOUNT_TYPE`  VARCHAR(6) NOT NULL  ,
`D_CREATE`  datetime  NOT NULL  ,
`S_STATE`  VARCHAR(6)    NOT NULL ,
`D_VALIDITY_PERIOD_START`  datetime NOT NULL  ,
`D_VALIDITY_PERIOD_END`   datetime  NOT NULL  ,
PRIMARY KEY (`N_ID`)
)
;

CREATE TABLE `SN_PAY`.`PAY_ORDER_DISCOUNT_EDIT` (
`N_ID`  integer NOT NULL AUTO_INCREMENT ,
`N_MERCHANT_ID`  integer UNSIGNED NOT NULL    ,
`N_PAYMENT_ID`   integer UNSIGNED NOT NULL    ,
`N_VALUE`  decimal(10,2) NOT NULL     ,
`S_CALC_STANDARD`  VARCHAR(6)  NOT NULL  ,
`S_DISCOUNT_TYPE`  VARCHAR(6)  NOT NULL  ,
`D_CREATE`  datetime   NOT NULL    ,
`S_STATE`  VARCHAR(1) NOT NULL    ,
`D_VALIDITY_PERIOD_START`  datetime  NOT NULL    ,
`D_VALIDITY_PERIOD_END`   datetime  NOT NULL    ,
PRIMARY KEY (`N_ID`)
)
;

CREATE TABLE `SN_PAY`.`PAY_ORDER_DISCOUNT_RECORD` (
`N_ID`  integer NOT NULL AUTO_INCREMENT ,
`N_MERCHANT_ID`  integer UNSIGNED NOT NULL    ,
`N_PAYMENT_ID`   integer UNSIGNED NOT NULL    ,
`S_ORDER_NO`  VARCHAR(60)   ,
`S_PAYPARTNER_OTHER_ORDER_NO`  VARCHAR(60)   ,
`N_DISCOUNT_ID`  integer UNSIGNED NOT NULL    ,
`N_MONEY`  decimal(10,2) NOT NULL     ,
`D_CREATE`  datetime   NOT NULL    ,
PRIMARY KEY (`N_ID`)
)
;
